# Generated by Django 3.2 on 2021-04-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210420_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='last_login',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
    ]
