# Generated by Django 3.2 on 2021-04-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_isclosed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
